language: python

python:
    - 2.7
    - 3.5
    - 3.6

sudo: false

env:
    global:
        - NUMPY_VERSION=1.13
        - ASTROPY_VERSION=stable
        - SETUP_CMD='test'
        - CONDA_CHANNELS='astropy'
        - CONDA_DEPENDENCIES='Cython scipy matplotlib shapely>=1.6 astropy-healpix'
        - PIP_DEPENDENCIES='pytest-arraydiff'
        - SETUP_XVFB=True

    matrix:
        # Make sure that egg_info works without dependencies
        - SETUP_CMD='egg_info'

matrix:
    include:

        # Do a coverage test in Python 2.
        - python: 2.7
          env: SETUP_CMD='test --coverage'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: 2.7
          env: SETUP_CMD='build_sphinx -w'

        # Try Astropy development version
        - python: 3.6
          env: ASTROPY_VERSION=development

        # Try older numpy/astropy versions
        - python: 3.6
          env: NUMPY_VERSION=1.11 ASTROPY_VERSION=2.0
        - python: 2.7
          env: NUMPY_VERSION=1.10 ASTROPY_VERSION=2.0

        # Try without optional dependencies
        - python: 2.7
          env: PIP_DEPENDENCIES='pytest-arraydiff'
        - python: 3.6
          env: PIP_DEPENDENCIES='pytest-arraydiff'

before_install:
    # Make sure matplotlib uses PyQT not PySide
    - export QT_API=pyqt

install:
    - git clone git://github.com/astrofrog/ci-helpers.git
    - cd ci-helpers; git checkout pytest-lts; cd ..
    - source ci-helpers/travis/setup_conda.sh

script:
   - python setup.py $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='reproject/tests/coveragerc'; fi
